entities:
  - Echantillon

drug_type:
  - 'Cannabis'

relations:
  - http://www.stups.fr/ontologies/2023/stups/estProcheDe

target_relations:
  - http://www.stups.fr/ontologies/2023/stups/estProcheDe

network:
  - graph_db_host: "host.docker.internal"

# entities_limit: 1